### ISSUE TITLE
variables non set

### ISSUE THREAD

**Issue by lgrandco** [mynameisjul/minishell#118]
warning quand on la variable n'est pas trouvee
![image](https://github.com/mynameisjul/minishell/assets/108620622/2a51c70b-a250-4f47-9822-bc3e0698d377)
segfault avec redir
![image](https://github.com/mynameisjul/minishell/assets/108620622/7f5223fc-a7e3-49be-9de7-14368839db18)

**Comment by croueAlec** [comment]
le premier est corrige sur la branche actuelle (117), le deuxieme, lol j'ai la flemme et pas le temps. merci pour ton aide
